//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public int ID { get; set; }
        public string Article { get; set; }
        public string Article1 { get; set; }
        public string Name { get; set; }
        public string Short_Name { get; set; }
        public int languages_ID { get; set; }
        public string ISO { get; set; }
    
        public virtual language language { get; set; }
    }
}
