//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int Id { get; set; }
        public string tlang { get; set; }
        public string olang { get; set; }
        public string sdate { get; set; }
        public string anum { get; set; }
        public string atitle { get; set; }
        public string count { get; set; }
        public string prep { get; set; }
        public string stitle { get; set; }
        public string gdoc { get; set; }
        public string bar { get; set; }
        public string symh { get; set; }
        public string dist { get; set; }
        public string date { get; set; }
        public string ldate { get; set; }
        public string dname { get; set; }
        public string loca { get; set; }
        public string snum { get; set; }
        public string mnum { get; set; }
        public string file { get; set; }
        public string org { get; set; }
        public string entity { get; set; }
        public string doctype { get; set; }
        public string category { get; set; }
        public string lname1 { get; set; }
        public string lname2 { get; set; }
        public string subcat { get; set; }
    }
}
