//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentitySample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class final_temp
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public int categories_ID { get; set; }
        public string Symbole { get; set; }
        public int Count { get; set; }
        public string Reg { get; set; }
    
        public virtual category category { get; set; }
    }
}
